### ISSUE TITLE
no HTML5 location over http in Chrome 50+

### ISSUE THREAD

**Issue by jgravois** [twaddington/pdxroasters#125]
www.pdxroasters.com doesn't appear to have a valid SSL cert, so folks using Chrome 50+ can no longer provide HTML5 location to sort coffeeshops based on proximity.

if you're able to provision one and redirect automatically to `https`  (i did this for free recently with a gh-pages site using Cloudfare) that would be pretty darn cool.

ps. i tried to give this feedback via the site, but I encountered a `500` error when attempting to submit the form.

**Comment by twaddington** [comment]
Thanks for the report @jgravois. I hadn't realized Chrome had made that change. Seems like a sensible thing to do.

We're looking into adding SSL support but it's kind of expensive on Heroku ($20/mo + cost of cert). We may go ahead and do it anyway but I need to chat with the other folks who work on the site first.

**Comment by paulcpederson** [comment]
@jgravois you're a gentleman and a scholar
